// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_error from "./routes/_error.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $docs_slug_ from "./routes/docs/[...slug].tsx";
import * as $docs_middleware from "./routes/docs/_middleware.ts";
import * as $docs_index from "./routes/docs/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $raw from "./routes/raw.ts";
import * as $Counter from "./islands/Counter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_error.tsx": $_error,
    "./routes/_middleware.ts": $_middleware,
    "./routes/docs/[...slug].tsx": $docs_slug_,
    "./routes/docs/_middleware.ts": $docs_middleware,
    "./routes/docs/index.tsx": $docs_index,
    "./routes/index.tsx": $index,
    "./routes/raw.ts": $raw,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
